- name: Download Cardano Mainnet Config Files
  hosts: localhost
  gather_facts: false
  vars:
    dest_dir: "/home/danu/git/cardano-master-config"
    base_url: "https://book.play.dev.cardano.org/environments/mainnet"

    files:
      - url: "{{ base_url }}/config.json"
        dest: "mainnet-config-relay.json"
      - url: "{{ base_url }}/config-bp.json"
        dest: "mainnet-config-bp.json"        
      - url: "{{ base_url }}/topology-non-bootstrap-peers.json"
        dest: "mainnet-topology-relay.json"
      - url: "{{ base_url }}/byron-genesis.json"
        dest: "mainnet-byron-genesis.json"
      - url: "{{ base_url }}/shelley-genesis.json"
        dest: "mainnet-shelley-genesis.json"
      - url: "{{ base_url }}/alonzo-genesis.json"
        dest: "mainnet-alonzo-genesis.json"
      - url: "{{ base_url }}/conway-genesis.json"
        dest: "mainnet-conway-genesis.json"

  tasks:
    - name: Create destination directory
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: Download and rename config files
      ansible.builtin.get_url:
        url: "{{ item.url }}"
        dest: "{{ dest_dir }}/{{ item.dest }}"
        mode: '0644'
      loop: "{{ files }}"