- name: 04-libsodium_Install_and_Cleanup
  hosts: localhost
  vars_files:
    - update_param.yml

  tasks:
    - name: Ensure git directory exists
      file:
        path: "{{ user_home }}/git"
        state: directory
        mode: '0755'

    - name: Remove existing libsodium git directory
      file:
        path: "{{ user_home }}/git/libsodium"
        state: absent

    - name: Clone libsodium repository
      git:
        repo: https://github.com/input-output-hk/libsodium
        dest: "{{ user_home }}/git/libsodium"
        version: "{{ libsodium_version }}"
        force: yes

    - name: Install autotools packages
      package:
        name:
          - autotools-dev
          - autoconf
          - automake
          - libtool
        state: present
      become: yes

    - name: Run autogen.sh with timeout and fallback
      shell: |
        timeout 300 ./autogen.sh >> {{ log_file }} 2>&1 || {
          echo "autogen.sh timed out or failed, using fallback method..."
          # Clean any corrupted files
          git clean -fdx
          git reset --hard HEAD
          # Use system config.guess and config.sub if available
          if [ -f /usr/share/automake-*/config.guess ]; then
            cp /usr/share/automake-*/config.guess build-aux/
          fi
          if [ -f /usr/share/automake-*/config.sub ]; then
            cp /usr/share/automake-*/config.sub build-aux/
          fi
          # Run autoreconf as alternative
          autoreconf -fiv
        }
      args:
        chdir: "{{ user_home }}/git/libsodium"
      register: autogen_result

    - name: Configure libsodium
      shell: |
        if [ ! -f configure ]; then
          echo "Configure script not found, running autoreconf..."
          autoreconf -fiv
        fi
        ./configure --prefix=/usr/local >> {{ log_file }} 2>&1
      args:
        chdir: "{{ user_home }}/git/libsodium"

    - name: Build libsodium
      shell: make >> {{ log_file }} 2>&1
      args:
        chdir: "{{ user_home }}/git/libsodium"

    - name: Run tests (make check)
      shell: make check >> {{ log_file }} 2>&1
      args:
        chdir: "{{ user_home }}/git/libsodium"

    - name: Install libsodium
      shell: make install >> {{ log_file }} 2>&1
      args:
        chdir: "{{ user_home }}/git/libsodium"
      become: yes

    - name: Update shared library cache
      command: ldconfig
      become: yes
